coverage:
  status:
    project:
      default:
        target: auto
      core:
        flags:
          - core
        target: auto
    patch: off

flags:
  core:
    paths:
      - internal/agent/
      - internal/protocol/
